demosaba/Models/MVClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace demosaba.Models
{
    public class MVClass
    {
        public string DOCUMENTO { get; set; }
        public string CLIENTE { get; set; }
        public DateTime FECHA { get; set; }
        public string NOMBRE { get; set; }

        public string NIT_RECEPTOR { get; set; }

        public string CLAVE { get; set; }

        public string CODIGO_MONEDA { get; set; }

        public string TOTALGRAVADO { get; set; }

        public string TOTALEXENTO { get; set; }

        public string TOTALDESCUENTOS { get; set; }

        public string TOTALIMPUESTO { get; set; }

        public string TOTALCOMPROBANTE { get; set; }

        public bool CONTIENE_ERRORES { get; set; }

        public bool ERROR_WS { get; set; }

        public bool ERROR_SOFTLAND { get; set; }

        public bool ENVIADO { get; set; }

        public bool ACEPTADO { get; set; }

        public string RESPUESTA_XML { get; set; }
        public string PDF { get; set; }

        public string XML { get; set; }

        public string var { get; set; }


    }
}

demosaba/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace demosaba.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

demosaba/Controllers/demoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using demosaba.Models;


namespace demosaba.Controllers
{
    public class demoController : Controller
    {
        // GET: demo
        public ActionResult Index()
        {
            string mainconn = ConfigurationManager.ConnectionStrings["Myconnection"].ConnectionString;
            SqlConnection sqlconn = new SqlConnection(mainconn);
            string sqlquery = "set dateformat dmy select top 200 * from [erpadmin].[P_APP_HACIENDA_DE] ";
            SqlCommand sqlcomm = new SqlCommand(sqlquery, sqlconn);
            sqlconn.Open();
            SqlDataAdapter sda = new SqlDataAdapter(sqlcomm);
            DataSet ds = new DataSet();
            sda.Fill(ds);
            List<MVClass> lc = new List<MVClass>();
            foreach(DataRow dr in ds.Tables[0].Rows)
            {
                var con_err = Convert.ToString(dr["CONTIENE_ERRORES"]);
                var con_errws = Convert.ToString(dr["ERROR_WS"]);
                var con_soft = Convert.ToString(dr["ERROR_SOFTLAND"]);
                var acept = Convert.ToString(dr["ACEPTADO"]);
                var envia = Convert.ToString(dr["ENVIADO"]);
                var error = true;
                var error2 = true;
                var error3 = true;
                var var_env = false;
                var var_acep = false;
                if (con_err == "N")
                {
                    error = false;
                }
                if (con_errws == "N")
                {
                    error2 = false;
                }
                if (con_soft == "N")
                {
                    error3 = false;
                }
                if (envia == "S")
                {
                    var_env = true;
                }
                if (acept == "A")
                {
                    var_acep = true;
                }
                lc.Add(new MVClass
                {
                    DOCUMENTO = Convert.ToString(dr["DOCUMENTO"]),
                    CLIENTE = Convert.ToString(dr["CLIENTE"]),
                    FECHA = Convert.ToDateTime(dr["FECHA"]),
                    NOMBRE = Convert.ToString(dr["NOMBRE"]),
                    NIT_RECEPTOR = Convert.ToString(dr["NIT_RECEPTOR"]),
                    CODIGO_MONEDA = Convert.ToString(dr["CODIGO_MONEDA"]),
                    CLAVE = Convert.ToString(dr["CLAVE"]),
                    TOTALGRAVADO = Convert.ToString(dr["TOTALGRAVADO"]),
                    TOTALEXENTO = Convert.ToString(dr["TOTALEXENTO"]),
                    TOTALDESCUENTOS = Convert.ToString(dr["TOTALDESCUENTOS"]),
                    TOTALIMPUESTO = Convert.ToString(dr["TOTALIMPUESTO"]),
                    TOTALCOMPROBANTE = Convert.ToString(dr["TOTALCOMPROBANTE"]),
                    CONTIENE_ERRORES = error,
                    ERROR_WS = error2,
                    ERROR_SOFTLAND = error3,
                    ENVIADO = var_env,
                    ACEPTADO = var_acep,
                    RESPUESTA_XML = Convert.ToString(dr["RESPUESTA_XML"]),
                    PDF = Convert.ToString(dr["PDF"]),
                    XML = Convert.ToString(dr["XML"]),
                    var = "/pdd/prueba.pdf"


                }); ;

            }

            sqlconn.Close();
            ModelState.Clear();
            return View(lc);
        }

        [HttpPost]
        public ActionResult Index(DateTime? start, DateTime? end)
        {

            string mainconn = ConfigurationManager.ConnectionStrings["Myconnection"].ConnectionString;
            SqlConnection sqlconn = new SqlConnection(mainconn);
            string sqlquery = "set dateformat dmy select  * from [erpadmin].[P_APP_HACIENDA_DE] where FECHA between '" + start + "'and'" + end + "'";
            SqlCommand sqlcomm = new SqlCommand(sqlquery, sqlconn);
            sqlconn.Open();
            SqlDataAdapter sda = new SqlDataAdapter(sqlcomm);
            DataSet ds = new DataSet();
            sda.Fill(ds);
            List<MVClass> lc = new List<MVClass>();
            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                var con_err = Convert.ToString(dr["CONTIENE_ERRORES"]);
                var con_errws = Convert.ToString(dr["ERROR_WS"]);
                var con_soft = Convert.ToString(dr["ERROR_SOFTLAND"]);
                var acept = Convert.ToString(dr["ACEPTADO"]);
                var envia = Convert.ToString(dr["ENVIADO"]);
                var error = true;
                var error2 = true;
                var error3 = true;
                var var_env = false;
                var var_acep = false;
                if (con_err == "N")
                {
                    error = false;
                }
                if (con_errws == "N")
                {
                    error2 = false;
                }
                if (con_soft == "N")
                {
                    error3 = false;
                }
                if (envia == "S")
                {
                    var_env = true;
                }
                if (acept == "A")
                {
                    var_acep = true;
                }
                lc.Add(new MVClass
                {

                    DOCUMENTO = Convert.ToString(dr["DOCUMENTO"]),
                    CLIENTE = Convert.ToString(dr["CLIENTE"]),
                    FECHA = Convert.ToDateTime(dr["FECHA"]),
                    NOMBRE = Convert.ToString(dr["NOMBRE"]),
                    NIT_RECEPTOR = Convert.ToString(dr["NIT_RECEPTOR"]),
                    CODIGO_MONEDA = Convert.ToString(dr["CODIGO_MONEDA"]),
                    CLAVE = Convert.ToString(dr["CLAVE"]),
                    TOTALGRAVADO = Convert.ToString(dr["TOTALGRAVADO"]),
                    TOTALEXENTO = Convert.ToString(dr["TOTALEXENTO"]),
                    TOTALDESCUENTOS = Convert.ToString(dr["TOTALDESCUENTOS"]),
                    TOTALIMPUESTO = Convert.ToString(dr["TOTALIMPUESTO"]),
                    TOTALCOMPROBANTE = Convert.ToString(dr["TOTALCOMPROBANTE"]),
                    CONTIENE_ERRORES = error,
                    ERROR_WS = error2,
                    ERROR_SOFTLAND = error3,
                    ENVIADO = var_env,
                    ACEPTADO = var_acep,
                    RESPUESTA_XML = Convert.ToString(dr["RESPUESTA_XML"]),
                    PDF = Convert.ToString(dr["PDF"]),
                    XML = Convert.ToString(dr["XML"]),
                    var = "/pdd/pp.XML"
                });
                
            }

            sqlconn.Close();
            ModelState.Clear();
            return View(lc);
        }
    }
}

demosaba/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

demosaba/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

demosaba/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

demosaba/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

demosaba/Views/demo/Index.cshtml
@model IEnumerable<demosaba.Models.MVClass>

@{
    ViewBag.Title = "Index";
}

<center>
    <h2>Lista de facturas</h2>

    <p>
        @using (Html.BeginForm("Index", "demo", FormMethod.Post))
        {

            <input type="date" name="start"  />
            <input type="date" name="end" />
            <input type="submit" name="submit" value="Search"/>
        }
    </p>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.DOCUMENTO)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CLIENTE)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FECHA)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NOMBRE)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NIT_RECEPTOR)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CLAVE)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CODIGO_MONEDA)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TOTALGRAVADO)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TOTALEXENTO)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TOTALDESCUENTOS)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TOTALIMPUESTO)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TOTALCOMPROBANTE)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CONTIENE_ERRORES)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ERROR_WS)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ERROR_SOFTLAND)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ENVIADO)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ACEPTADO)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RESPUESTA_XML)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PDF)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.XML)
                </th>

                <th></th>
            </tr>
        </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DOCUMENTO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CLIENTE)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FECHA)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NOMBRE)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NIT_RECEPTOR)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CLAVE)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CODIGO_MONEDA)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TOTALGRAVADO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TOTALEXENTO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TOTALDESCUENTOS)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TOTALIMPUESTO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TOTALCOMPROBANTE)
                    </td>
                    <td>
                        
                            @Html.DisplayFor(modelItem => item.CONTIENE_ERRORES)
                        
                        
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ERROR_WS)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ERROR_SOFTLAND)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ENVIADO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ACEPTADO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.XML)
                    </td>
                    <td>
                        <a class="btn-danger" href="file://///C:/Users/CGS/Desktop/Nuevo%20documento%20de%20texto%20(2).txt" target="_blank" rel="noopener noreferrer">PDF</a>
                    </td>
                    <td>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
                           XML
                        </button>


                        <!-- Modal -->
                        <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <?xml version="1.0" encoding="ISO-8859-1" ?>
                                        <embed  src="@item.var" class="w-800" height="500" width="500" />
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <a class="btn btn-success" href="@item.var" target="_blank">Abrir Nueva pestana</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>


                </tr>
            }

    </table>
</center>